version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    command: python app.py
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    command: python backend_service.py
